### ISSUE TITLE
Having Issues with a book in spanish

### ISSUE THREAD

**Issue by siba2893** [aedocw/epub2tts-edge#24] opened 2024-05-27 15:08 UTC
<img width="1228" alt="image" src="https://github.com/aedocw/epub2tts-edge/assets/2425158/23276f48-3fd6-46d7-88ac-9b7248b8e0ab">

**Comment by aedocw** [comment] 2024-05-27 21:07
looks like for some reason nltk did not download punkt (it's supposed to do that automatically on the first run I think).

Try launching python (with `python`) and running:
```
import nltk
nltk.download("punkt")
```
If that runs without error, type `exit()` to get out of python, and try running epub2tts-edge again.

**Comment by aedocw** [comment] 2024-06-08 15:11
Have you had a chance to try this again? I suspect it's not a bug as I have not been able to reproduce in a clean environment, but if you are able to reproduce this reliably please let me know.

**Comment by aedocw** [comment] 2024-06-26 19:58
I'm reluctant to add code to address an issue that is likely not easily reproduced. It could have been a temporary networking problem on the users end, or something else weird with their environment. If this is a common thing that multiple people are hitting it would be worth trying to find a reliable way to trigger the download on it's own, but generally NLTK is supposed to handle it.

**Comment by erfansamandarian** [comment] 2024-06-26 20:05
For what it's worth, I've gotten the same message every time I've tried to install on a system without the nltk folder in my home folder. This didn't happen in epub2tts as far as I remember.

**Comment by aedocw** [comment] 2024-06-26 20:16
Ah ok, that is interesting! Makes me think I should spend a little more time trying to recreate that in clean environments then.

**Comment by prydom** [comment] 2024-06-27 03:54
I setup in a fresh [distrobox](https://github.com/89luca89/distrobox) and Python virtual environment yesterday since I don't use an Debian-based distro and encountered the same error.

Note that running the code directed in the error message created a directory tree in ~/nltk_data without asking where I wanted it saved. If that could be configured save the token models in the Python lib (meaning it would end up in the virtual environment tree) directory instead, that would be helpful.
```
~ $ tree nltk_data
nltk_data
└── tokenizers
    ├── punkt
    ├── punkt
    │   ├── PY3
    │   │   ├── README
    │   │   ├── czech.pickle
[...]
```

**Comment by aedocw** [comment] 2024-06-27 13:28
I'm not sure yet about how to specify where nltk stores the models, but for a start I'll add this which should handle the fetching:

```
def ensure_punkt(self):
    try:
        nltk.data.find("tokenizers/punkt")
    except LookupError:
        nltk.download("punkt")
```

**Comment by aedocw** [comment] 2024-06-28 00:22
This was resolved with https://github.com/aedocw/epub2tts-edge/pull/31

**Closed by aedocw** 2024-06-28 00:22 UTC
Labels: bug
